version: '2'

services:

  client:
    container_name: client
    build: ../frontend
    depends_on:
      - server
    ports:
      - "8000:8000"


  server:
    container_name: server
    build: ./
    ports:
      - "8080:8080"
